apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: custom-app-container
        image: pratham0100/custom-app:v1
        ports:
        - containerPort: 9090
